ci: adjust failure conditions

diff --git a/.github/workflows/build-commerce-schematic.yml b/.github/workflows/build-commerce-schematic.yml
--- a/.github/workflows/build-commerce-schematic.yml
+++ b/.github/workflows/build-commerce-schematic.yml
@@ -189,8 +189,10 @@ jobs:
 
       - name: Verify ng add failed
         if: matrix.ng-add-succeed == false && steps.ng-add.outcome != 'failure'
-        run: echo "ERROR: ng add was expected to fail but succeeded" && exit 1
+        run: |
+          echo "ERROR: ng add was expected to fail but succeeded" && exit 1
 
       - name: Verify ng build failed
         if: matrix.build-succeed == false && steps.ng-build.outcome != 'failure'
-        run: echo "ERROR: ng build was expected to fail but succeeded" && exit 1
+        run: |
+          echo "ERROR: ng build was expected to fail but succeeded" && exit 1
